version: '3.7'

services:
  db:
    image: mariadb
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - mysql_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - db:/var/lib/mysql
      - ./secrets/init:/docker-entrypoint-initdb.d

  wp:
    image: wordpress
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME_FILE: /run/secrets/mysql_database
      WORDPRESS_DB_USER_FILE: /run/secrets/mysql_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - wp:/var/www/html

  wp2:
    image: wordpress
    secrets:
      - mysql_database2
      - mysql_user2
      - mysql_password2
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME_FILE: /run/secrets/mysql_database2
      WORDPRESS_DB_USER_FILE: /run/secrets/mysql_user2
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password2
    volumes:
      - wp2:/var/www/html

  wp3:
    image: wordpress
    secrets:
      - mysql_database3
      - mysql_user3
      - mysql_password3
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME_FILE: /run/secrets/mysql_database3
      WORDPRESS_DB_USER_FILE: /run/secrets/mysql_user3
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_password3
    volumes:
      - wp3:/var/www/html

  adminer:
    image: adminer
    ports:
      - "8080:8080"
#      - "443:443"

  nginx:
    image: nginx
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./secrets/certs:/etc/nginx/certs

volumes:
  db:
  wp:      
  wp2:      
  wp3:      

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password
  mysql_database:
    file: ./secrets/mysql_database
  mysql_database2:
    file: ./secrets/mysql_database2
  mysql_database3:
    file: ./secrets/mysql_database3
  mysql_user:
    file: ./secrets/mysql_user
  mysql_user2:
    file: ./secrets/mysql_user2
  mysql_user3:
    file: ./secrets/mysql_user3
  mysql_password:
    file: ./secrets/mysql_password
  mysql_password2:
    file: ./secrets/mysql_password2
  mysql_password3:
    file: ./secrets/mysql_password3
